"""add unique constraint on recurring_id date

Revision ID: 0b7c1f841d21
Revises: a93f898c5c67
Create Date: 2026-06-11 16:16:37.490245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7c1f841d21'
down_revision: Union[str, Sequence[str], None] = 'a93f898c5c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recurring_transaction_date', 'transactions', ['recurring_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recurring_transaction_date', 'transactions', type_='unique')
    # ### end Alembic commands ###
